version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kamel1234
 
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kamel1234
      ME_CONFIG_MONGODB_URL: mongodb://root:kamel1234@mongo:27017/
    depends_on:
        - mongo
    restart: always
      
  boardserver:
    build: .
    ports:
        - 5000:80
    depends_on:
        - mongo